web:
  build: ./web
  ports: 
    - "8080:80"
  links:
    - db
  volumes:
    - ./app:/var/www
    - ./app/web:/var/www/html

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"
